In [1]:
import numpy as np

X = [[20,2],
     [25,5],
     [30,3],
     [35,8],
     [40,6]]

y = [30,45,50,60,65]

X = np.array(X)
X = np.c_[np.ones(X.shape[0]), X]
y = np.array(y)
print(X.shape,y.shape)

X.T @ y

print("Rule:",np.linalg.inv((X.T @ X) )@ (X.T @ y))

(5, 3) (5,)
Rule: [0.93457944 1.4635514  1.07476636]


# Attention

In [2]:
import numpy as np

# Matriks Query (Q) - Ukuran [3, 4]
Q = np.array([
    [2, 0, 1, 3],
    [0, 4, 1, 1],
    [3, 1, 0, 2]
], dtype=np.float32)

# Matriks Key (K) - Ukuran [3, 4]
K = np.array([
    [1, 3, 0, 2],
    [2, 0, 4, 1],
    [0, 1, 1, 3]
], dtype=np.float32)

# Matriks Value (V) - Ukuran [3, 4]
V = np.array([
    [3, 1, 4, 2],
    [1, 5, 0, 3],
    [2, 2, 6, 1]
], dtype=np.float32)

# --- VERIFIKASI DIMENSI ---
print("Dimensi Q:", Q.shape)  # Output: (3, 4)
print("Dimensi K:", K.shape)  # Output: (3, 4)
print("Dimensi V:", V.shape)  # Output: (3, 4)

Q,K,V

Dimensi Q: (3, 4)
Dimensi K: (3, 4)
Dimensi V: (3, 4)


(array([[2., 0., 1., 3.],
        [0., 4., 1., 1.],
        [3., 1., 0., 2.]], dtype=float32),
 array([[1., 3., 0., 2.],
        [2., 0., 4., 1.],
        [0., 1., 1., 3.]], dtype=float32),
 array([[3., 1., 4., 2.],
        [1., 5., 0., 3.],
        [2., 2., 6., 1.]], dtype=float32))

In [3]:
def softmax(arr):
    hasil = []
    for x in arr:
        hasil.append(np.exp(x)/np.sum(np.exp(arr)))

    return hasil

arr = [4,1,-2]
softmax(arr)

[np.float64(0.9503302116973792),
 np.float64(0.047314155221824035),
 np.float64(0.0023556330807966803)]

In [4]:
Q = np.array(Q)
K = np.array(K)
V = np.array(V)

softmax((Q @ K.T)/np.sqrt(4)) @ V

array([[0.38181896, 0.85255889, 0.60028435, 0.5368459 ],
       [1.84668546, 0.68574702, 2.55197583, 1.23665969],
       [0.30643953, 0.26397967, 0.42893382, 0.26728265]])

In [10]:
TP = 31
FP = 13
TN = 2556
FN = 34

PRECISION = TP/(TP+FP)
RECALL = TP/(TP+FN)
F1_SCORE = 2*PRECISION*RECALL/(PRECISION+RECALL)


PRECISION,RECALL,F1_SCORE

(0.7045454545454546, 0.47692307692307695, 0.5688073394495413)